### ISSUE TITLE
Rewrite it in python

### ISSUE THREAD

**Issue by bernes1** [tacotacoenchilada/rocket-example#1]

**Comment by tacotacoenchilada** [comment]
![balls-nigga](https://user-images.githubusercontent.com/74435721/202875871-48d29b58-ed49-44a3-84aa-f5704ead36b0.gif)

**Comment by tacotacoenchilada** [comment]
Ill rewrite it in a minute, do you have any specifications, like what packages to you use whateva

**Comment by bernes1** [comment]
fastapi

**Comment by bernes1** [comment]
django
